Repository girlscriptsiliguri/official-website, pull requests merged in 2022-10, with the labels that each got.

#1 Update README.md
  README.md
Labels: good first issue, hacktoberfest, contributions-welcome

#2 Update HACKTOBERFEST.md
  HACKTOBERFEST.md
Labels: hacktoberfest, contributions-welcome, hacktoberfest-accepted

#4 Update gssiliguri.md
  gssiliguri.md
Labels: documentation, good first issue, hacktoberfest, contributions-welcome, hacktoberfest-accepted

#5 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, good first issue, hacktoberfest, contributions-welcome, hacktoberfest-accepted

#7 [docs]: created code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#9 Create design prototype file
  UI_UX/design prototype file
Labels: enhancement, hacktoberfest, contributions-welcome, hacktoberfest-accepted
